abstract-robot-dynamics: CjrlRobotDynamicsObjectFactory Class Reference
CjrlRobotDynamicsObjectFactory Class Reference
The creation of an object.
#include <abstract-robot-dynamics/robot-dynamics-object-constructor.hh>
Public Member Functions
virtual ~CjrlRobotDynamicsObjectFactory ()
Destructor.
virtual CjrlDynamicRobot * createDynamicRobot ()=0
Construct and return a pointer to a dynamic robot.
virtual CjrlHumanoidDynamicRobot * createHumanoidDynamicRobot ()=0
Construct and return a pointer to a humanoid dynamic robot.
virtual CjrlJoint * createJointFreeflyer (const matrix4d &inInitialPosition)=0
Construct and return a pointer to a freeflyer joint.
virtual CjrlJoint * createJointRotation (const matrix4d &inInitialPosition)=0
Construct and return a pointer to a rotation joint.
virtual CjrlJoint * createJointTranslation (const matrix4d &inInitialPosition)=0
Construct and return a pointer to a translation joint.
virtual CjrlBody * createBody ()=0
Construct and return a pointer to a body.
virtual CjrlHand * createHand (const CjrlJoint *inWristJoint)=0
Construct and return a pointer to a hand.
virtual CjrlFoot * createFoot (const CjrlJoint *inAnkle)=0
Construct and return a pointer to a foot.
Detailed Description
The creation of an object.
Constructor & Destructor Documentation
virtual CjrlRobotDynamicsObjectFactory::~CjrlRobotDynamicsObjectFactory () [inline, virtual]
Destructor.
References createBody(), createDynamicRobot(), createFoot(), createHand(), createHumanoidDynamicRobot(), createJointFreeflyer(), createJointRotation(), and createJointTranslation().
Member Function Documentation
virtual CjrlBody* CjrlRobotDynamicsObjectFactory::createBody () [pure virtual]
Construct and return a pointer to a body.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlDynamicRobot* CjrlRobotDynamicsObjectFactory::createDynamicRobot () [pure virtual]
Construct and return a pointer to a dynamic robot.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlFoot* CjrlRobotDynamicsObjectFactory::createFoot (const CjrlJoint * inAnkle) [pure virtual]
Construct and return a pointer to a foot.
Parameters:
inAnkle The joint the foot is attached to.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlHand* CjrlRobotDynamicsObjectFactory::createHand (const CjrlJoint * inWristJoint) [pure virtual]
Construct and return a pointer to a hand.
Parameters:
inWristJoint The joint the hand is attached to.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlHumanoidDynamicRobot* CjrlRobotDynamicsObjectFactory::createHumanoidDynamicRobot () [pure virtual]
Construct and return a pointer to a humanoid dynamic robot.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlJoint* CjrlRobotDynamicsObjectFactory::createJointFreeflyer (const matrix4d & inInitialPosition) [pure virtual]
Construct and return a pointer to a freeflyer joint.
Parameters:
inInitialPosition position of the local frame of the joint when the robot is in initial configuration.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlJoint* CjrlRobotDynamicsObjectFactory::createJointRotation (const matrix4d & inInitialPosition) [pure virtual]
Construct and return a pointer to a rotation joint.
Parameters:
inInitialPosition position of the local frame of the joint when the robot is in initial configuration.
Referenced by ~CjrlRobotDynamicsObjectFactory().
virtual CjrlJoint* CjrlRobotDynamicsObjectFactory::createJointTranslation (const matrix4d & inInitialPosition) [pure virtual]
Construct and return a pointer to a translation joint.
Parameters:
inInitialPosition position of the local frame of the joint when the robot is in initial configuration.
Referenced by ~CjrlRobotDynamicsObjectFactory().